services:
    server-test:
        build:
            context: .
            dockerfile: ./docker/test/Dockerfile
        image: laravel-php84-server-test
        container_name: laravel-php84-server-test
        ports:
            - "8080:80"
        environment:
            - APP_ENV=test
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=
            - DB_PORT=
            - DB_DATABASE=
            - DB_USERNAME=
            - DB_PASSWORD=
        restart: always
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge