services:
    server-test:
        build:
            context: .
            dockerfile: ./docker/test/Dockerfile
        image: laravel-php84-server-test
        container_name: laravel-php84-server-test
        ports:
            - "9000:80"
        environment:
            - APP_ENV=test
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=192.168.64.1
            - DB_PORT=3306
            - DB_DATABASE=laravel-php84-test
            - DB_USERNAME=root
            - DB_PASSWORD=123456
        restart: always
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge