services:
    server-dev:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        image: laravel-php84-server-dev
        container_name: laravel-php84-server-dev
        ports:
            - "8080:80"
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=
            - DB_PORT=
            - DB_DATABASE=
            - DB_USERNAME=
            - DB_PASSWORD=
        restart: always
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge